<a href="https://colab.research.google.com/github/UPino25/MAT422/blob/main/UlisesPinoHW1.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Principle Component Analysis**


1.   What is Principle Component Analysis?
2.   1.4.1 Singular Value Decomposition
3.   Examples of Singular Value Decomposition




## 1. What is Principle Component Analysis?

Principle analysis is commonly used for dimensionally reduction by projecting data point onto only the first few principle components to obtain lower-dimensional data while preserving as much of the data's variation as possible. Its underlying mathematics can be explained with singular value decomposition.

## 2. 1.4.1 Singular Value Decomposition
Let A be an $m$ x $n$ matrix. Then $A^T$$A$ is symmetric and can be orthogonally diagonialized. Let $\mathrm{v_1,...,v_2}$ be an orthonormal basis for $R^n$ consisting of eigenvectors of $A^T$$A$, and let $\lambda_1,...,\lambda_n$ be the associated eigenvalues of $A^T$$A$. Then for $1 \le i \le n,$


$||Av_i||^2 = (Av_i)^TAv_i = v^T_iA^TAv_i$

$= v^T_i(\lambda v_i)$ since $\mathrm{v_i}$ is an eigenvectors of $A_T$$A$
 (1.4.1)

$ = \lambda_i$ since $\mathrm{v_i}$ is a unit vector

So the eigenvalues of $A$ are all nonnegative. By renumbering, if necessary, we may assume that the eigenvalues are arranged that

$$\lambda_1 \ge \lambda_2 \ge ... \lambda_n \ge 0.$$

The singluar values of $A$ are the square roots of the eigenvalues of $A^TA,$ denoted by $\sigma_1,...,\sigma_n,$ and they are arranged in decreasing order. That is, $\sigma_i = \sqrt{\lambda_i}$ for $1 \le i \le n.$ The singular values of A are the lengths of the vectors $Av_1,...,Av_n$.

Theorem 1.4.1 If an $m$ x $n$ matrix $A$ has $r$ nonzero singular vales, $\sigma_1,...,\sigma_r \ge 0$ with $\sigma_{r+1} = ... = \sigma_n = 0$, then the dimension of col($A$) $ = r$

Theorem 1.4.2 (The Singular Value Decomposition) Let $A$ be an $m$ x $n$ matrix with the dimension of col($A$) $ = r.$ Then there exists an $m$ x $n$ matrix $\sum,$ where the diagonal entries in $D$ are the first $r$ singular values of $A$ $\sigma_1 \ge \sigma_2 \ge ... \sigma_r \ge 0,$ and there exist an $m$ x $m$ orthogonal matrix $U$ and an $n$ x $n$ orthogonal matrix $V$ such that

$$A = U \sum V^T$$

Any factorization $A = U \sum V^T,$ with $U$ and $V$ orthhogonal and $\sum,$ is called a singular value decomposition SVD of $A.$ The matrices $U$ and $V$ are not unique, but the diagonal entries of $\sum$ are necessarily the singular values of $A$. The column of $U$ in such a decomposition are called left singular vectors of $A,$ and the column of $V$ are called right singular vectors of $A.$

## Examples of Singular Value Decomposition

In [4]:
import numpy as np

### Calculate the singular value decomposition with a 3D array

## Our 3D Array
NumPyArray = np.array([[1,4,7],[10,13,16],[19,22,25]])


## This function allows us to get our Singlue Value Decomposition
U,S,V = np.linalg.svd(NumPyArray, compute_uv = True)
print("The result is: ")

# This prints out our singular value
print("S: ", S)

print("U: ", U)

print("V: ", V)




The result is: 
S:  [4.52568969e+01 3.57956491e+00 2.94855300e-15]
U:  [[-0.16486479  0.8978602   0.40824829]
 [-0.50580579  0.27837716 -0.81649658]
 [-0.84674678 -0.34110589  0.40824829]]
V:  [[-0.47089202 -0.57147894 -0.67206587]
 [-0.78204478 -0.08212888  0.61778702]
 [ 0.40824829 -0.81649658  0.40824829]]
