<a href="https://colab.research.google.com/github/UPino25/MAT422/blob/main/UlisesPinoHW1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.3 Linear** **Regression**

1.   What is linear regression?
2.   QR Decomposition




## 1. What is linear regression?


*   Linear Regression is used frequently in practical applications because of
its simplicty. The models depend linearly on their unknown parameteres and
therefore are easier to fit than models which are non-linearly related to their
parameters. As a result, the statistical properties of the resulting estimators
are easier to determine.





## 2. 1.3.1 QR Decomposition


> QR decomposition is a useful procedure to solve the linear least squares problem. First we use the Gram-Schmidt algorithm to obtain an orthonormal basis span(a1,...,a2) from a linearly independent set of span(a1,...,a2). In order to derive QR decomposition, let

\begin{align}
        A = \begin{pmatrix}
        \ | &  & | \\
        \ a_1 &...& a_2 \\
        \ | &  & |
        \end{pmatrix}
    \end{align}

and \begin{align}
        Q = \begin{pmatrix}
        \ | &  & | \\
        \ q_1 &...& q_2 \\
        \ | &  & |
        \end{pmatrix}
    \end{align}

where A, Q are *n x m* matrices. The output of the Gram-Schmidt algorithm above can then be written in the following compact form, known as QR decomposition in Figure 1.3

$A = QR$.

where column *i* of the *m X m* matrix *R* contains the coefficients of the linear combination of
$q_j$'s that produces $a_i$. $Q$ is a $R^{nxm}$ matrix with $Q^T$$Q$ = $I_{mxm}$. It may be easier to verify $A = QR$ by

$A^T$ = $R^T$$Q^T$

By the proof of Gran-Schmidt,
\begin{align}
a_i \in span(q_1,...,q_2).
 \end{align}
So column i of $R$ has only zeros below the diagonal. Hence $R$ has a special structure: it is upper triangular.











In [12]:
import numpy as np


# Our First Matrix
NumPyArray = np.array([[4,5],[8,10]])

print(NumPyArray)

# Find the Decomposition of the NumPyArray Matrix
Q, R = np.linalg.qr(NumPyArray)

print("Below is our QR decomposition: ")

print('\nQ:\n', Q)
print('\nR:\n', R)

[[ 4  5]
 [ 8 10]]
Below is our QR decomposition: 

Q:
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

R:
 [[ -8.94427191 -11.18033989]
 [  0.           0.        ]]
