Important Concepts:


# **1.2 Elements of Linear Algebra**

The following from the list below will be covered:

1. Intro to NumPy Arrays
2. 1.2.4 Eigenvalues and Eigenvectors



## **Intro to Numpy Arrays**

In [38]:
# This allows us to access the NumPy library and import its functions.
import numpy as np

### Creating a basic array
## Our first array
List1 = [1,2,3,4,5,6,7]
NumPyArray = np.array(List1)
print("Array from List 1: ", NumPyArray)

## Our second array
List2 = [10, 11, 12, 13 ,14 ,15]
NumPyArray2 = np.array(List2)
print("Array from List 2: ", NumPyArray2)

### Creating Array Elements
## Using the zeros command
np.zeros(7)
print(np.zeros(7))

### Creating a specific array with range of elements
np.arange(1,11,2)

### Accessing an array's element
NumPyArray3 = np.array([[10,11,12],[21,22,23],[32,33,34]])

## Accessing second element of NumPyArray3
print(NumPyArray3[1])

### Reshaping Arrays
NumPyArray4 = np.arange(8)
print(NumPyArray4)

## Reshape NumPyArray4 into 4 by 3 array
NumPyArray5 = NumPyArray4.reshape(4,2)
print(NumPyArray5)



Array from List 1:  [1 2 3 4 5 6 7]
Array from List 2:  [10 11 12 13 14 15]
[0. 0. 0. 0. 0. 0. 0.]
[21 22 23]
[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


##  **1.2.4 Eigenvalues and Eigenvectors**

Eigenvalues and eigenvectors are key concepts in many applications. As before, we work on R^d.
Definition 1.2.21 (Eigenvalues and eigenvectors):

Let A ∈ R^dxd be a square matrix. Then λ ∈ R is an eigenvalue of A if there exists a nonzero vector x ≠ 0 such that

A**x** = λ**x**. (1.2.3)

The vector **x** is referred to as an eigenvector.



In [45]:
### Calculating our eigenvalues and eigenvectors
import numpy as np

## Real Eigenvalues and Eigenvectors
NumPyArray6 = np.array([[2,4],[6,8]])
eigenvalues, eigenvectors = np.linalg.eig(NumPyArray6)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

## No Real Eigenvalues
NumPyArray7 = np.array([[0,-2],[2,0]])
eigenvalues, eigenvectors = np.linalg.eig(NumPyArray7)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

Eigenvalues:  [-0.74456265 10.74456265]
Eigenvectors:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Eigenvalues:  [0.+2.j 0.-2.j]
Eigenvectors:  [[ 0.        -0.70710678j  0.        +0.70710678j]
 [-0.70710678+0.j         -0.70710678-0.j        ]]
